### ISSUE TITLE
NCEPLIBS-bufr documentation ?

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/NOAA-EMC.github.io#15]
I could not find the NCEPLIBS-bufr documentation. There have been updates to the documentation to include information on how to use python interfaces. Are there plans to connect that documentation to the github.io interface ?

**Comment by edwardhartnett** [comment]
See https://noaa-emc.github.io/NCEPLIBS-bufr/

I am not actually sure what NOAA-EMC.github.io is and who is supposed to updated it.

@Hang-Lei-NOAA are you the one who keeps this site up to date?

**Comment by jbathegit** [comment]
From the main page https://github.com/NOAA-EMC/NCEPLIBS-bufr, you can scroll down to the README file where it says:

For full documentation see https://noaa-emc.github.io/NCEPLIBS-bufr/

Then, once you're there, you'll see where it says:

The python API documentation is available [here](https://noaa-emc.github.io/NCEPLIBS-bufr/python/index.html)

Click that, and it takes you to the Python docs.

**Comment by aerorahul** [comment]
@arunchawla-NOAA 
`noaa-emc.github.io` should contain documentation for `noaa-emc`.  Its `master` branch contains documentation for repositories under `noaa-emc` organization.  It could contain links to the components documentation, but the components documentation should reside within the repository of the component.

**Comment by arunchawla-NOAA** [comment]
ok I opened another issue for this. Can we discuss there ? We can close this issue as the documentation is there. It would help to have a clean landing page to go to documentation, but that should be functional
