### ISSUE TITLE
Improving the github.io interface

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/NOAA-EMC.github.io#16]
Can we update this ? I cannot see the link to the NCEPLIBS-bufr documentation and there are bullets to things that have no documentation. Plus when I follow the path I get the directories and not the html page links

https://noaa-emc.github.io/

**Comment by arunchawla-NOAA** [comment]
This link is at the top of our repositories page. Can we please clean this up ? It does not look good at all

**Comment by aerorahul** [comment]
This repository needs to be cleaned up.  The documentation uploaded here should be removed.  It does not belong in this repository.

**Comment by arunchawla-NOAA** [comment]
are all the doxygen html files uploaded here ? I have put a number of people here just for discussion. Final task will be assigned later. I just want to get a scope of what is happening here

**Comment by arunchawla-NOAA** [comment]
For NCEPLIBS-bufr and from what I can see for some of the other repos the html files have been generated and stored in gh-pages branches. Is that true ? Can we then just delete the html files loaded here ? @MinsukJi-NOAA can you confirm for me where the html files for NEMS and FV3 dycore are ?

**Comment by arunchawla-NOAA** [comment]
We need to have a standard approach for everything. Then the github.io should only contain links to the landing pages
